name: Cord Engine Quality Inspection
description: Performs linting, testing, and code review on Cord Engine Projects

runs:
  using: composite
  steps:
    - name: Harden runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          bun.sh:443
          github.com:443
          api.github.com:443
          objects.githubusercontent.com:443
          registry.npmjs.org:443
          securityscorecards.dev:443
          api.securityscorecards.dev:443
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      with:
        bun-version-file: package.json
    - name: Setup cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
    - name: Run quality checks
      run: |
        bun install --frozen-lockfile
        bun lint:ci
        bun lint:tsc
        bun lint:markdown
      shell: bash
    - name: Dependency review
      if: github.event_name == 'pull_request'
      uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
