name: DCO Assistant

on:
  workflow_call:
    secrets:
      WORKFLOW_PAT:
        required: true

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  dco-assistant:
    name: Verify DCO Signatures
    runs-on: ubuntu-latest
    steps:
      - if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Developer Certificate of Origin and affirm that by signing and signing off my commits using git, I am certifying that my contributions comply.') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        with:
          path-to-signatures: "signatures/version1/dco.json"
          path-to-document: "https://github.com/CordEngine/.github/blob/main/DCO"
          branch: "main"
          allowlist: bot*
          remote-organization-name: CordEngine
          remote-repository-name: dco-signatures
          custom-notsigned-prcomment: "> [!IMPORTANT]\nThank you for your contribution to Cord Engine. To protect the integrity of the code base, we require that all contributions comply with the [Developer Certificate of Origin](https://github.com/CordEngine/.github/blob/main/DCO).\n\nPlease copy and post the text below in a comment on this PR to affirm that by [signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and [signing off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) your commits using git, you certify the code complies with the Developer Certificate of Origin.\n\nThis step is only required once, and we will save your certification for future contributions."
          custom-pr-sign-comment: "I have read the Developer Certificate of Origin and affirm that by signing and signing off my commits using git, I am certifying that my contributions comply."
          lock-pullrequest-aftermerge: true
          use-dco-flag: true
      - if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['🪪 status: DCO Signed']
            })
