name: PR

on:
  workflow_call:

jobs:
  validate-template:
    uses: cordengine/.github/.github/workflows/pr-template-validation.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_body: ${{ github.event.pull_request.body }}

  ci:
    needs: validate-template
    uses: cordengine/.github/.github/workflows/lint.yml@main

  label:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Add ready for review label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.addLabels({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              labels: ['🐰 status: ready for review']
            });
